# Project information
site_name: Bi_RNN_DVC_MKDOCS
# defeine TOC or order of website-
nav:
  - Home: index.md
  - Page 2: page_02.md

site_author: Anoop Srivastava
site_description: >-
  DESCRIPTION

# Repository
repo_name: srivanoo21/Bi_RNN_DVC_MKDOCS
repo_url: https://github.com/srivanoo21/Bi_RNN_DVC_MKDOCS

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
 
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/srivanoo21"  target="_blank" rel="noopener">Anoop Srivastava</a>